### ISSUE TITLE
Readme.md file is missing.

### ISSUE THREAD

**Issue by shubham0354** [Roshan13046/Website-for-Tech-Summit-Conference#1]
Readme.md file is missing.

**Comment by zippytyro** [comment]
Hey, @Roshan13046 I found that your conference details page is not responsive and it doesn't follow the theme of the login page. I would like to improve that. Should I open another issue to contribute?

I can also add form submission functionality using netlify's feature - check this form -  https://deimos-survey.netlify.app/

Will be waiting for your reply.

**Comment by Roshan13046** [comment]
> Hey, @Roshan13046 I found that your conference details page is not responsive and it doesn't follow the theme of the login page. I would like to improve that. Should I open another issue to contribute?
> 
> I can also add form submission functionality using netlify's feature - check this form - https://deimos-survey.netlify.app/
> 
> Will be waiting for your reply.

Go ahead.
First Create a new issue, then start with the new branch and work on it.

**Comment by zippytyro** [comment]
fine @Roshan13046 will make a PR soon.
